### PR TITLE
Update 2.28 PR to 2.28.9

### PR DESCRIPTION
**Pull request by bearbin**
Latest version of the stable release, various security/bug fixes.

### CODE REVIEW

**Comment by bearbin** [comment]
Tested and cuberite builds, I have updated cuberite/cuberite#5540

**Comment by 12xx12** [comment]
Do we merge #5 or #6?

**Comment by bearbin** [comment]
#6 then #5 (assuming this one looks good to you)

**Comment by 12xx12** [comment]
Yeah. This is the release brach so we're good to go

**Pull request merged**
